spring:
  application:
    name: spring-cloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/osmondpomare/spring-cloud-config
          search-paths: ${application}
      fail-fast: true
      allow-override: true
      override-none: true
      override-system-properties: false
