server:
  port: 8888

spring:
  application:
    name: cloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/osmondpomare/spring-cloud-config
          search-paths: '{application}'
      fail-fast: true
      allow-override: true
      override-none: true
      override-system-properties: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true