management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  boot:
    admin:
      ui:
        public-url: http://local.services/admin

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      startup: ${random.int}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true